### PR TITLE
compatibility with Valve's "fullscreen hack"

### PR DESCRIPTION
**Pull request by dhewg**
Valve's proton [0] has a "fullscreen hack", single patch at [1], which doesn't switch the resolution for fullscreen games anymore, but instead scales the game window to the root window. Apparently that's the only way to ensure efficient page flips.

I ran into this with a new 4k display, and that hack solves it. Without page flips games not using the desktop resolution become unplayable due to heavy stuttering [2].

This patch makes nine compatible with Valve's hack. I choose to not hide the scaling behind an envvar or similar, but just scale to whatever window size wine gave us. This is what dxvk does too [3].

[0] https://github.com/ValveSoftware/Proton
[1] https://github.com/doitsujin/dxvk/files/2497953/fs_hack.patch.gz
[2] https://github.com/doitsujin/dxvk/issues/713
[3] https://github.com/doitsujin/dxvk/commit/56e9bba27950206a997d5f2524c5c49c54b5787b

### CODE REVIEW

**Comment by dhewg** [comment]
Oh, I forgot to mention that this patch only works properly with the mesa nine patches [0] pushed today by @axeldavy and the unfinished [0] on top!

[0] https://gitlab.freedesktop.org/mesa/mesa/compare/7e64e39f8bb54e45cc76dcd33d38537696e53a44...2318ca68bbeb4fa6e21a4d8c650cec3f64246596
[1] https://github.com/iXit/Mesa-3D/commit/09312339bb66419a9b1fdfcae007b7601d62475c

**Comment by dhewg** [comment]
fyi @aeikum, in case nine is considered

**Comment by siro20** [comment]
Need tests to make sure it doesn't introduce regressions. 
How can it be tested without Proton?

**Comment by dhewg** [comment]
That would be rather easy I guess.

Without proton (or fs_hack.patch applied to wine) it shouldn't change anything. So one just needs to check if a game properly scales in fullscreen mode as it did before.

If it doesn't the mouse cursor would be off too, so a regression would be quick to notice.

**Pull request merged**
