### PR TITLE
configure: Update changes to include/config.h.in

### PR DESCRIPTION
**Pull request by gryffus**
This commit updates include/config.h.in with changes from https://github.com/iXit/wine/commit/d52244d60d7cd9cf7baf94f8fb290bc93f3463a2

### CODE REVIEW

**Comment by siro20** [comment]
Can you explain why these changes are necessary?

**Comment by gryffus** [comment]
I don't think it is necessary, but if you run autoreconf and then try to commit some changes, this diff keeps messing the commit, if you don't notice. I thought it would be better to commit this separately instead of part of some future commit.

**Comment by axeldavy** [comment]
we need the input of some wine maintainers on this.

**Comment by gryffus** [comment]
From wine folks:
[15:03] <aeikum> gryffus: if you're submitting it to wine-patches for inclusion in wine, then you should not include changes to generated files like configure and config.h.in. they'll be generated by the maintainer when the patch is accepted
[15:04] <aeikum> for example, https://www.winehq.org/pipermail/wine-patches/2016-January/145744.html
[15:04] <aeikum> no config.h.in changes in the patch, but when it was turned into commit 0c9b94eeb3bcf5f4b049de934b11f5a8dab0afda, it has those changes
[15:05] <aeikum> but if you're just doing it in your local tree, then you should generate those files yourself so they take effect properly
[15:07] <aeikum> gryffus: the reason for that policy in wine is different developers have different versions of e.g. autotools, so they may generate files with unrelated changes
[15:07] <aeikum> so we just have only one person generate the files, which is the maintainer who accepts the commit
[15:07] <aeikum> that way the autotools version is always the same
[15:09] <puk> afair Staging has the same rule
[15:10] <puk> but the rule is a "you should not" not a "you must not"

So it looks that not only include/config.h.in, but also configure changes _must not_ be in the patches/comits. Only the ones in configure.ac.

**Pull request closed without merging**
